### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by ukazap** [atom-minimap/minimap-highlight-selected#36] opened 2017-02-28 04:45 UTC
[Enter steps to reproduce:]

1. Disable `minimap` package
2. Return to open files tab

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package 4.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of null

```
At /Users/jurnal/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:56

TypeError: Cannot read property 'forEach' of null
    at MinimapHighlightSelected.markersDestroyed (/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:56:17)
    at MinimapHighlightSelected.markersDestroyed (/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:1:1)
    at /packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:39:50
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at HighlightedAreaView.module.exports.HighlightedAreaView.removeMarkers (/packages/highlight-selected/lib/highlighted-area-view.coffee:179:14)
    at HighlightedAreaView.removeMarkers (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:84:6)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:52:8
```

### Commands

```
     -3:00.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.tinted-tab-bar.compact-tab-bar.panel-shadows.panel-contrast.compact-tree-view.blend-tree-view.theme-atom-material-syntax.theme-atom-material-ui)
     -1:30.8.0 settings-view:open (input.hidden-input)
  2x -1:18.9.0 core:backspace (input.hidden-input)
     -0:35.5.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
  2x -0:19.9.0 core:close (button.btn.icon.enablement.icon-playback-play)
     -0:07.4.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
aurora-theme 1.2.2 
autocomplete-modules 1.6.7 
blame 0.10.2 
color-picker 2.2.5 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-jsx-props 1.2.5 
file-icons 2.0.15 
git-blame 0.4.11 
git-plus 7.3.3 
highlight-selected 0.12.0 
indent-guide-improved 1.4.12 
linter 1.11.23 
linter-eslint 8.1.2 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
monokai-seti 0.7.0 
open-recent 5.0.0 
pigments 0.39.0 
platformio-ide-terminal 2.3.1 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
project-manager 3.3.3 
seti-ui 1.6.1 
symbols-tree-view 0.13.2 
todo-show 1.11.0 
```

**Comment by jonyeezs** [comment] 2017-03-17 00:23
most probably duplicate of #33

**Closed** 2017-04-05 11:31 UTC
